---
- name: Ensure packages are installed
  apt:
    name: "{{ glpiinventoryagent_pkgs }}"
  tags: [glpiinventoryagent]

- name: Ensure GlpiinventoryAgent package is available
  apt:
    deb: "{{ glpiinventoryagent_deb }}"
  tags: [glpiinventoryagent]
