---
- name: Ensure packages are installed
  apt:
    name: "{{ glpiinventoryagent_pkgs }}"
  when: glpi_install_pkgs
  tags: [glpiinventoryagent]

- name: Ensure GlpiinventoryAgent package is available
  apt:
    deb: "{{ glpiinventoryagent_deb }}"
  when: glpi_install_pkgs
  tags: [glpiinventoryagent]

- name: Creates Work Directory
  file: path="{{ glpi_workdir }}" state=directory

- name: Creates Inventory Directory
  file: path="{{ glpi_inventorydir }}" state=directory

- name: Download Installer
  get_url: url="{{ glpiagenturl }}" dest="{{ glpi_workdir }}" mode=0755

- name: Run Installer
  cmd: "{{ glpiagentinstaller }} -s "{{ glpiinventoryagent_server_url }}" -l "{{  glpi_inventorydir }}" --type=all -v"
