---
- name: Load disto specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: [always, glpiinventoryagent]

- name: Include distro specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  tags: [always, glpiinventoryagent]


- name: Ensure configuration file is updated
  template:
    src: agent.cfg
    dest: "{{ glpiinventoryagent_configdir }}/{{ glpiinventoryagent_configfile }}"
    mode: 0640
  tags: [always, glpiinventoryagent, cfg]
  register: configfile

- name: Ensure execution through CRON
  cron:
    name: Glpiinventory run
    state: present
    user: root
    job: "{{ glpi_batch_command }}"
    weekday: '1'
    hour: '*'
    minute: '*'
    #minute: "{{ 59|random(seed=inventory_hostname) }}"
  when: glpi_crontab
