---
- name: Ensure execution through CRON
  cron:
    name: Glpiinventory run
    state: present
    user: root
    job: "{{ glpi_batch_command }}"
    day: '1'
    hour: '1'
    minute: '0'
    #minute: "{{ 59|random(seed=inventory_hostname) }}"
  when: glpi_crontab
